name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Service-Management
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Service-Management/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests
      - name: Run tests
        run: ./mvnw test
      - name: Build Docker image
        run: docker build -t europe-west3-docker.pkg.dev/virtual-dynamo-505500-r2/servicemanagementsystem-repo/servicemanagementsystem:${{ github.sha }} .

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Push Docker image
        run: docker push europe-west3-docker.pkg.dev/virtual-dynamo-505500-r2/servicemanagementsystem-repo/servicemanagementsystem:${{ github.sha }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: servicemanagementsystem-cluster
          location: europe-west3

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/servicemanagementsystem-deployment servicemanagementsystem=europe-west3-docker.pkg.dev/virtual-dynamo-505500-r2/servicemanagementsystem-repo/servicemanagementsystem:${{ github.sha }}
          kubectl rollout status deployment/servicemanagementsystem-deployment